# Site settings -----------------------------------
title: ONLI Lyon
email: clairezuliani@gmail.com
description: L'Observatoire Numérique Libertés - Identités est un laboratoire de recherche spécialisé en cybergraphie.
# baseurl: "/jekyll-starter" # the subpath of your site, e.g. /blog
# url: "https://clairezed.github.io" # the base hostname & protocol for your site
url: "https://lahaut.netlify.com" # the base hostname & protocol for your site

# Social settings ------------------------------------
github_username: clairezed
twitter_username: ZooletteDesBois

# Build settings --------------------------------------
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


# Sass ------------------------------------------------

sass:
  sass_dir: _sass
  sourcemap: true
  style: compressed


# Locale ----------------------------------------------

timezone: Europe/Paris
encoding: utf-8
locale: fr

# Includes ----------------------------------------------
include:
  - _pages

# defaults ----------------------------------------------

defaults:
  -
    scope:
      path: "_pages" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "post"
      permalink: /:basename

# variables ---------------------------------------------

format:
  date_format: "%b %-d, %Y"       # NOVEMBER 1, 2015
  meta_date_format: "%Y-%m-%d"  # 2015-11-01

header_pages:
  - _pages/about.md
  - _pages/components.html
