# Site settings -----------------------------------
title: ONLI Lyon
description: L'Observatoire Numérique Libertés - Identités est un laboratoire de recherche spécialisé en cybergraphie.
# baseurl: "/jekyll-starter" # the subpath of your site, e.g. /blog
# url: "https://clairezed.github.io" # the base hostname & protocol for your site
url: "https://lahaut.netlify.com" # the base hostname & protocol for your site

# Social settings ------------------------------------
email: contact@aadn.org
github_username: clairezed
twitter_username: aadnlyon
facebook_username: aadn.profil
instagram_username: aadnlyon

# Build settings --------------------------------------
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


# Sass ------------------------------------------------

sass:
  sass_dir: _sass
  sourcemap: true
  style: compressed


# Locale ----------------------------------------------

timezone: Europe/Paris
encoding: utf-8
locale: fr

# Includes ----------------------------------------------
include:
  - _pages

# Collections -------------------------------------------

collections:
  team_members:
    output: true
    permalink: /equipe/:path/
    title: Equipe

# defaults ----------------------------------------------

defaults:
  -
    scope:
      path: "_pages" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "post"
      permalink: /:basename

# variables ---------------------------------------------

format:
  date_format: "%b %-d, %Y"       # NOVEMBER 1, 2015
  meta_date_format: "%Y-%m-%d"  # 2015-11-01

header_pages:
  - _pages/quest-ce-que-la-cybergraphie.md
  - _pages/qui-sommes-nous.md
