# Site settings -----------------------------------
title: La haut lite
email: clairezuliani@gmail.com
description: My own jekyll starter
# baseurl: "/jekyll-starter" # the subpath of your site, e.g. /blog
# url: "https://clairezed.github.io" # the base hostname & protocol for your site
url: "https://lahaut.netlify.com" # the base hostname & protocol for your site

# Social settings ------------------------------------
github_username: clairezed
twitter_username: ZooletteDesBois

# Build settings --------------------------------------
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


# Sass ------------------------------------------------

sass:
  sass_dir: _sass
  style: compressed


# Locale ----------------------------------------------

timezone: Europe/Paris
encoding: utf-8
locale: fr

# Includes ----------------------------------------------
include:
  - _pages

# variables ----------------------------------------------

format:
  date_format: "%b %-d, %Y"       # NOVEMBER 1, 2015
  meta_date_format: "%Y-%m-%d"  # 2015-11-01
