backend:
  name: github
  repo: clairezed/lahaut-lite # Path to your Github repository
  branch: master # Branch to update

# # interface for drafting, reviewing, and approving posts.
# publish_mode: editorial_workflow

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "articles" # Used in routes, e.g. /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Categories (séparées par ',')", name: "categories", widget: "list", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Terrain", name: "territory", widget: "select", options: ["Villefranche", "Saint Denis"], default: "Villefranche"}
      # - {label: "Author", name: "author", widget: "relation", collection: "authors", searc}
      - {label: "En page d'accueil", name: "highlighted", widget: "boolean", default: :false}
      # - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["first_name", "last_name"], valueField: "title"}
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
  - name: "pages" # Used in routes, e.g. /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    # slug: "{{permalink}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      # - {label: "slug", name: "permalink", widget: "string"}
  - name: "team" # Used in routes, e.g. /admin/collections/blog
    label: "Equipe" # Used in the UI
    folder: "_team_members" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    # slug: "{{permalink}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
