backend:
  name: github
  repo: clairezed/lahaut-lite # Path to your Github repository
  branch: master # Branch to update

# # interface for drafting, reviewing, and approving posts.
# publish_mode: editorial_workflow

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
  - name: "pages" # Used in routes, e.g. /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    # slug: "{{permalink}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      # - {label: "slug", name: "permalink", widget: "string"}
